### ISSUE TITLE
Creating url:undefined  TypeError: Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by dendisuhubdy** [sand500/SlackLateX#7]
```
Creating url:undefined

TypeError: Cannot read property 'protocol' of undefined
    at WebSocketClient.connect (/root/node_modules/websocket/lib/WebSocketClient.js:137:18)
    at createWS (/root/SlackLateX/bot.js:55:12)
    at Request._callback (/root/SlackLateX/bot.js:23:13)
    at Request.self.callback (/root/node_modules/request/request.js:186:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/root/node_modules/request/request.js:1081:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/root/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)

```

**Comment by sand500** [comment]
You need to make a file called secret.txt and put either the api token from the bots integration or your own token from
https://api.slack.com/docs/oauth-test-tokens
